version: '3'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API、Web UI 端口
      - "6334:6334"  # gRPC 端口
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped